# Generated by Django 3.0.3 on 2020-03-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizenreport',
            name='multiple',
        ),
        migrations.AlterField(
            model_name='citizenreport',
            name='status',
            field=models.CharField(blank=True, choices=[('unread', 'Unread'), ('marked', 'Marked'), ('started', 'Action Started'), ('completed', 'Action completed'), ('dismissed', 'Action dismissed')], max_length=20, null=True),
        ),
    ]
